In [1]:
import pandas as pd
import numpy as np

In [3]:
# Path to the dataset
data_path = "dataset/processed_inputs.csv"  # Update path as needed

# Load the dataset
df = pd.read_csv(data_path)

# Display the first few rows
print("Dataset Preview:")
df

Dataset Preview:

,PatientID,State,Sex,GeneralHealth,AgeCategory,HeightInMeters,WeightInKilograms,BMI,HadAngina,HadStroke,...,ChestScan,RaceEthnicityCategory,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos,HadHeartAttack
0,1,Alabama,Female,Fair,Age 75 to 79,1.63,84.820000,32.099998,1,0,...,1,"White only, Non-Hispanic",0,0,0,1,"No, did not receive any tetanus shot in the pa...",0,1,0
1,2,Alabama,Female,Very good,Age 65 to 69,1.60,71.669998,27.990000,0,0,...,0,"White only, Non-Hispanic",0,0,1,1,"Yes, received Tdap",0,0,0
2,3,Alabama,Male,Excellent,Age 60 to 64,1.78,71.209999,22.530001,0,0,...,0,"White only, Non-Hispanic",1,0,0,0,"Yes, received tetanus shot but not sure what type",0,0,0
3,4,Alabama,Male,Very good,Age 70 to 74,1.78,95.250000,30.129999,0,0,...,0,"White only, Non-Hispanic",0,0,1,1,"Yes, received tetanus shot but not sure what type",0,0,0
4,8,Alaska,Female,Fair,Age 60 to 64,1.70,87.540001,30.230000,0,0,...,0,"Black only, Non-Hispanic",0,0,0,1,"No, did not receive any tetanus shot in the pa...",0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190152,237624,Puerto Rico,Female,Good,Age 55 to 59,1.57,68.040001,27.440001,1,0,...,0,Hispanic,1,0,0,0,"Yes, received Tdap",0,0,0
190153,237625,Puerto Rico,Female,Poor,Age 70 to 74,1.52,45.810001,19.730000,0,0,...,0,Hispanic,0,1,0,0,"Yes, received tetanus shot but not sure what type",0,0,0
190154,237626,Puerto Rico,Female,Good,Age 60 to 64,1.57,90.720001,36.580002,0,0,...,0,Hispanic,0,0,1,0,"No, did not receive any tetanus shot in the pa...",0,0,0
190155,237628,Puerto Rico,Male,Fair,Age 45 to 49,1.75,70.309998,22.889999,1,0,...,1,Hispanic,0,1,1,1,"Yes, received Tdap",1,0,1
190156,237630,Puerto Rico,Female,Good,Age 30 to 34,1.60,83.010002,32.419998,0,0,...,1,Hispanic,0,1,0,0,"No, did not receive any tetanus shot in the pa...",0,0,0

In [1]:
import pandas as pd

# Reload the dataset
file_path = 'dataset/processed_inputs.csv'
df = pd.read_csv(file_path)

# Select 10 random rows from the dataframe
random_entities = df.sample(n=10, random_state=42)

# Save the selected entities to a new CSV file
output_path = 'dataset/test.csv'
random_entities.to_csv(output_path, index=False)

output_path

'dataset/test.csv'